### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [sandeeep-prajapati/quantum_computer_resource#1]
I recently came across your project quantum_computer_resource and I noticed that the repository github.com/sandeeep-prajapati/quantum_computer_resource currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by sandeeep-prajapati** [comment]
I am currently a final-year student exploring quantum computer technology. To further my knowledge, I am utilizing the resources available on https://learning.quantum.ibm.com/

However, I am uncertain about the licensing requirements and the various types of licenses available. I want to ensure that my use of these resources does not infringe upon IBM's intellectual property rights.

If my actions are in violation of any licensing agreements, please inform me so that I may rectify the situation promptly. I am unfamiliar with the licensing process and do not wish to unintentionally misuse the resources.

**Comment by sandeeep-prajapati** [comment]
Ok tonight, i will do it...

Thank you sir

**Comment by sandeeep-prajapati** [comment]
added License in it

**Comment by cbjuan** [comment]
Thanks!
